# Permalinks
permalink:           pretty

# Setup
title:               Kelly Nelson
tagline:             First Data Science Blog
url:                 
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kelly Nelson
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://konelson.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
